name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    env:
      DISPLAY: ":99.0"

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
      - name: Setup
        uses: ./.github/actions/setup-tooling

      - name: Vet
        run: go vet -v

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Build
        run: |
          go build "-gcflags=all=-N -l" -v .
          env GOOS=js GOARCH=wasm go build -v .
          env GOOS=windows GOARCH=amd64 go build -v .
          env GOOS=windows GOARCH=386 go build -v .
