name: goreleaser

on:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: ./.github/actions/setup-tooling

      - name: Lint
        uses: golangci/golangci-lint-action@v3

      - name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: snapshot --rm-dist
